CREATE TABLE public.nfl_plays (
	play_id INTEGER DEFAULT NULL,
	game_id INTEGER DEFAULT NULL,
	home_team TEXT DEFAULT NULL,
	away_team TEXT DEFAULT NULL,
	posteam TEXT DEFAULT NULL,
	posteam_type TEXT DEFAULT NULL,
	defteam TEXT DEFAULT NULL,
	side_of_field TEXT DEFAULT NULL,
	yardline_100 INTEGER DEFAULT NULL,
	game_date DATE DEFAULT NULL,
	quarter_seconds_remaining INTEGER DEFAULT NULL,
	half_seconds_remaining INTEGER DEFAULT NULL,
	game_seconds_remaining INTEGER DEFAULT NULL,
	game_half TEXT DEFAULT NULL,
	quarter_end BOOL DEFAULT NULL,
	drive INTEGER DEFAULT NULL,
	sp BOOL DEFAULT NULL,
	qtr INTEGER DEFAULT NULL,
	down INTEGER DEFAULT NULL,
	goal_to_go BOOL DEFAULT NULL,
	time TIME DEFAULT NULL,
	yrdln TEXT DEFAULT NULL,
	ydstogo INTEGER DEFAULT NULL,
	ydsnet INTEGER DEFAULT NULL,
	description TEXT DEFAULT NULL,
	play_type TEXT DEFAULT NULL,
	yards_gained INTEGER DEFAULT NULL,
	shotgun BOOL DEFAULT NULL,
	no_huddle BOOL DEFAULT NULL,
	qb_dropback BOOL DEFAULT NULL,
	qb_kneel BOOL DEFAULT NULL,
	qb_spike BOOL DEFAULT NULL,
	qb_scramble BOOL DEFAULT NULL,
	pass_length TEXT DEFAULT NULL,
	pass_location TEXT DEFAULT NULL,
	air_yards INTEGER DEFAULT NULL,
	yards_after_catch INTEGER DEFAULT NULL,
	run_location TEXT DEFAULT NULL,
	run_gap TEXT DEFAULT NULL,
	field_goal_result TEXT DEFAULT NULL,
	kick_distance INTEGER DEFAULT NULL,
	extra_point_result TEXT DEFAULT NULL,
	two_point_conv_result TEXT DEFAULT NULL,
	home_timeouts_remaining INTEGER DEFAULT NULL,
	away_timeouts_remaining INTEGER DEFAULT NULL,
	timeout BOOL DEFAULT NULL,
	timeout_team TEXT DEFAULT NULL,
	td_team TEXT DEFAULT NULL,
	posteam_timeouts_remaining INTEGER DEFAULT NULL,
	defteam_timeouts_remaining INTEGER DEFAULT NULL,
	total_home_score INTEGER DEFAULT NULL,
	total_away_score INTEGER DEFAULT NULL,
	posteam_score INTEGER DEFAULT NULL,
	defteam_score INTEGER DEFAULT NULL,
	score_differential INTEGER DEFAULT NULL,
	posteam_score_post INTEGER DEFAULT NULL,
	defteam_score_post INTEGER DEFAULT NULL,
	score_differential_post INTEGER DEFAULT NULL,
	no_score_prob DECIMAL DEFAULT NULL,
	opp_fg_prob DECIMAL DEFAULT NULL,
	opp_safety_prob DECIMAL DEFAULT NULL,
	opp_td_prob DECIMAL DEFAULT NULL,
	fg_prob DECIMAL DEFAULT NULL,
	safety_prob DECIMAL DEFAULT NULL,
	td_prob DECIMAL DEFAULT NULL,
	extra_point_prob DECIMAL DEFAULT NULL,
	two_point_conversion_prob DECIMAL DEFAULT NULL,
	punt_blocked BOOL DEFAULT NULL,
	first_down_rush BOOL DEFAULT NULL,
	first_down_pass BOOL DEFAULT NULL,
	first_down_penalty BOOL DEFAULT NULL,
	third_down_converted BOOL DEFAULT NULL,
	third_down_failed BOOL DEFAULT NULL,
	fourth_down_converted BOOL DEFAULT NULL,
	fourth_down_failed BOOL DEFAULT NULL,
	incomplete_pass BOOL DEFAULT NULL,
	interception BOOL DEFAULT NULL,
	punt_inside_twenty BOOL DEFAULT NULL,
	punt_in_endzone BOOL DEFAULT NULL,
	punt_out_of_bounds BOOL DEFAULT NULL,
	punt_downed BOOL DEFAULT NULL,
	punt_fair_catch BOOL DEFAULT NULL,
	kickoff_inside_twenty BOOL DEFAULT NULL,
	kickoff_in_endzone BOOL DEFAULT NULL,
	kickoff_out_of_bounds BOOL DEFAULT NULL,
	kickoff_downed BOOL DEFAULT NULL,
	kickoff_fair_catch BOOL DEFAULT NULL,
	fumble_forced BOOL DEFAULT NULL,
	fumble_not_forced BOOL DEFAULT NULL,
	fumble_out_of_bounds BOOL DEFAULT NULL,
	solo_tackle BOOL DEFAULT NULL,
	safety BOOL DEFAULT NULL,
	penalty BOOL DEFAULT NULL,
	tackled_for_loss BOOL DEFAULT NULL,
	fumble_lost BOOL DEFAULT NULL,
	own_kickoff_recovery BOOL DEFAULT NULL,
	own_kickoff_recovery_td BOOL DEFAULT NULL,
	qb_hit BOOL DEFAULT NULL,
	rush_attempt BOOL DEFAULT NULL,
	pass_attempt BOOL DEFAULT NULL,
	sack BOOL DEFAULT NULL,
	touchdown BOOL DEFAULT NULL,
	pass_touchdown BOOL DEFAULT NULL,
	rush_touchdown BOOL DEFAULT NULL,
	return_touchdown BOOL DEFAULT NULL,
	extra_point_attempt BOOL DEFAULT NULL,
	two_point_attempt BOOL DEFAULT NULL,
	field_goal_attempt BOOL DEFAULT NULL,
	kickoff_attempt BOOL DEFAULT NULL,
	punt_attempt BOOL DEFAULT NULL,
	fumble BOOL DEFAULT NULL,
	complete_pass BOOL DEFAULT NULL,
	assist_tackle BOOL DEFAULT NULL,
	lateral_reception BOOL DEFAULT NULL,
	lateral_rush BOOL DEFAULT NULL,
	lateral_return BOOL DEFAULT NULL,
	lateral_recovery BOOL DEFAULT NULL,
	passer_player_id TEXT DEFAULT NULL,
	passer_player_name TEXT DEFAULT NULL,
	receiver_player_id TEXT DEFAULT NULL,
	receiver_player_name TEXT DEFAULT NULL,
	rusher_player_id TEXT DEFAULT NULL,
	rusher_player_name TEXT DEFAULT NULL

);

ALTER TABLE nfl_plays 
ADD ep DECIMAL DEFAULT NULL,
ADD epa DECIMAL DEFAULT NULL,
ADD total_home_epa DECIMAL DEFAULT NULL,
ADD total_away_epa DECIMAL DEFAULT NULL,
ADD total_home_rush_epa DECIMAL DEFAULT NULL,
ADD total_away_rush_epa DECIMAL DEFAULT NULL,
ADD total_home_pass_epa DECIMAL DEFAULT NULL,
ADD total_away_pass_epa DECIMAL DEFAULT NULL,
ADD air_epa DECIMAL DEFAULT NULL,
ADD yac_epa DECIMAL DEFAULT NULL,
ADD comp_air_epa DECIMAL DEFAULT NULL,
ADD comp_yac_epa DECIMAL DEFAULT NULL,
ADD total_home_comp_air_epa DECIMAL DEFAULT NULL,
ADD total_away_comp_air_epa DECIMAL DEFAULT NULL,
ADD total_home_comp_yac_epa DECIMAL DEFAULT NULL,
ADD total_away_comp_yac_epa DECIMAL DEFAULT NULL,
ADD total_home_raw_air_epa DECIMAL DEFAULT NULL,
ADD total_away_raw_air_epa DECIMAL DEFAULT NULL,
ADD total_home_raw_yac_epa DECIMAL DEFAULT NULL,
ADD total_away_raw_yac_epa DECIMAL DEFAULT NULL;

COPY nfl_plays FROM 'C:\Andy\SQL\NFL Play by Play 2009-2018 Simplified.csv'
WITH (
	FORMAT csv, 
	NULL 'NA',
	DELIMITER ',',
	HEADER
)
